### PR TITLE
remove theme scss from global styles

### PR DESCRIPTION
**Pull request by Dime**
Removed all theme SCSS from pathable-global-styles. Testing in preview doesn't show any issues from what I can tell.

Please check whether we still need this include, as it's empty now: pathable-app/client/main.scss

### CODE REVIEW

**Comment by RafaelVidaurre** [comment]
What base styles should `pathable-app` load now?

https://github.com/pathable/pathable-app/blob/master/client/main.scss

**Comment by Dime** [comment]
While back I moved the base styles to pathable-styles, and we're including them within the css modules. When I tested locally I had "pathable-app/blob/master/client/main.scss" empty, and didn't notice any changes in preview.

Are you sure we are getting base styles that are not in pathable-styles? Because if we do that needs to be changed so the css modules base styles are used. We really need to make a clear separation between the two, cause mixing them will make things more complicated.

**Comment by RafaelVidaurre** [comment]
This is the only line in `pathable-app`'s style file

`@import '{pathable-global-styles}/imports/theme.scss';`

**Comment by Dime** [comment]
Yes, I deleted that line when I tested in preview, but I didn't test in pathable-app.

**Comment by RafaelVidaurre** [comment]
please test in pathable app before we can merge this

**Comment by Dime** [comment]
We can delete this PR, because there's a better version on the latest PR, where some of the theme styles have been restructured and the unnecessary files deleted.

**Pull request closed without merging**
